site:
  name: MJ-CJM Blog
  site: 'http://localhost'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: MJ-CJM Blog
    template: '%s — MJ-CJM Blog'
  description: '云计算、边缘计算、Kubernetes、Docker 技术博客'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: MJ-CJM Blog
    type: website

i18n:
  language: zh-CN
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
    list:
      pathname: 'blog'
    category:
      pathname: 'category'
    tag:
      pathname: 'tag'
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

ui:
  theme: 'system'
